background {
    monitor =
    color = rgba(000000ff)
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(ffffffff)

    font_size = 64
    font_family = Sans

    position = 0, 100
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.2

    outer_color = rgba(ffffffff)
    inner_color = rgba(000000aa)
    font_color = rgba(ffffffff)

    position = 0, -100
    halign = center
    valign = center
}
